# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'player_turn.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QLabel,QMainWindow,QApplication,QDialog
import sys
import time
import ressources
from combat_code import *
from ennemy_turn import * 


class Ui_Dialog_player_turn(object):
    def setupUi(self, Dialog, pokemonDresseur, pokemonSauvage):
        Dialog.setObjectName("Dialog")
        Dialog.resize(985, 571)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(250, 130, 531, 321))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(320, 330, 151, 111))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(580, 250, 96, 96))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(510, 180, 246, 75))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(250, 250, 246, 75))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(230, 260, 225, 52))
        self.label_6.setStyleSheet("font: 75 8pt \"System\";")
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(420, 350, 171, 31))
        self.pushButton.setStyleSheet("font: 75 8pt \"System\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(610, 350, 121, 31))
        self.pushButton_2.setStyleSheet("font: 75 8pt \"System\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(420, 390, 171, 31))
        self.pushButton_3.setStyleSheet("font: 75 8pt \"System\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(490, 190, 225, 52))
        self.label_9.setStyleSheet("font: 75 8pt \"System\";")
        self.label_9.setObjectName("label_9")
        self.pokemonDresseur = pokemonDresseur
        self.pokemonSauvage = pokemonSauvage
        self.barreDeVieInitJoueur = pokemonDresseur.barreDeVie
        self.barreDeVieInitAdversaire = pokemonSauvage.barreDeVie
        self.nomPokemonJoueur = pokemonDresseur.nom
        self.nomPokemonSauvage = pokemonSauvage.nom

        self.retranslateUi(Dialog, pokemonDresseur, pokemonSauvage)  
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog, pokemonDresseur, pokemonSauvage):
        nomPokemonJoueur = pokemonDresseur.nom
        nomPokemonSauvage = pokemonSauvage.nom
        barreDeVieInitJoueur = pokemonDresseur.barreDeVie
        barreDeVieInitAdversaire = pokemonSauvage.barreDeVie
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/background/background/background3.png\"/></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/pokemons/pokemons/" + nomPokemonJoueur + "_back.png\"/></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/pokemons/pokemons/" + nomPokemonSauvage + "_front.png\"/></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/dialog_box/boxes/pngkey.com-dialogue-box-png-4529843(2).png\"/></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/dialog_box/boxes/pngkey.com-dialogue-box-png-4529843(2).png\"/></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">" + nomPokemonJoueur + "</span></p><p align=\"center\"><span style=\" font-weight:600;\">PV :" + str(barreDeVieInitJoueur) + " / " + str(barreDeVieInitJoueur) + "</span></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "> Attaque spéciale"))
        self.pushButton_2.setText(_translate("Dialog", "> Fuite"))
        self.pushButton_3.setText(_translate("Dialog", "> Attaque neutre"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">" + nomPokemonSauvage + "</span></p><p align=\"center\"><span style=\" font-weight:600;\">PV : " + str(barreDeVieInitAdversaire) + " / " + str(barreDeVieInitAdversaire) + "</span></p></body></html>"))
        
    def attaque_speciale(self) :
        _translate = QtCore.QCoreApplication.translate
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">" + self.nomPokemonSauvage + "</span></p><p align=\"center\"><span style=\" font-weight:600;\">PV : " + str(int(self.pokemonSauvage.barreDeVie)) + " / " + str(self.barreDeVieInitAdversaire) + "</span></p></body></html>"))
        #self.close() 


    def attaque_neutre(self) :
        _translate = QtCore.QCoreApplication.translate
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">" + self.nomPokemonSauvage + "</span></p><p align=\"center\"><span style=\" font-weight:600;\">PV : " + str(int(self.pokemonSauvage.barreDeVie)) + " / " + str(self.barreDeVieInitAdversaire) + "</span></p></body></html>"))
        #self.close()

    def fuite(self) :
        print("Fuite... !")
        self.close()
        
    def ButtonResponse(self, combat) :
        self.pushButton.clicked.connect(combat.attaque_speciale)
        self.pushButton.clicked.connect(self.attaque_speciale)
        
        self.pushButton.clicked.connect(combat.action_pokemon_sauvage)
        self.pushButton.clicked.connect(self.tour_ennemi)
        
        self.pushButton_3.clicked.connect(combat.attaque_neutre)
        self.pushButton_3.clicked.connect(self.attaque_neutre)
        
        self.pushButton_3.clicked.connect(combat.action_pokemon_sauvage)
        self.pushButton_3.clicked.connect(self.tour_ennemi)
        
        self.pushButton_2.clicked.connect(self.fuite)
    
    def close(self) :
        QApplication.instance().quit()
    
    def tour_ennemi(self) :
        
        if self.pokemonSauvage.barreDeVie == 0 :
            self.label_6.hide()
            self.label_4.hide()
            self.label_5.hide()
            self.label_9.hide()
            self.label_3.hide()
            self.label_3.setGeometry(QtCore.QRect(450, 270, 211, 51))
            self.label_3.setStyleSheet("font: 75 18pt \"System\";")
            self.label_3.setObjectName("label_3")
            _translate = QtCore.QCoreApplication.translate
            self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">VICTOIRE !!!</span></p><p><span style=\" font-weight:600;\"><br/></span></p></body></html>"))
            time.sleep(5) 
            print("Victoire ! ")
            self.close()
        
        time.sleep(4)
        self.pushButton.hide()
        self.pushButton_2.hide()
        self.pushButton_3.hide()
         
        _translate = QtCore.QCoreApplication.translate
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">" + self.nomPokemonJoueur + "</span></p><p align=\"center\"><span style=\" font-weight:600;\">PV :" + str(int(self.pokemonDresseur.barreDeVie)) + " / " + str(self.barreDeVieInitJoueur) + "</span></p></body></html>"))
         
        time.sleep(2)
        
        if self.pokemonDresseur.barreDeVie == 0 :
            self.label_6.hide()
            self.label_4.hide()
            self.label_5.hide()
            self.label_9.hide()
            self.label_2.hide()
            self.label_2.setGeometry(QtCore.QRect(440, 260, 97, 25))
            self.label_2.setStyleSheet("font: 75 18pt \"System\";")
            self.label_2.setObjectName("label_2")
            _translate = QtCore.QCoreApplication.translate
            self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Défaite...</span></p></body></html>"))
            time.sleep(5)
            print("Défaite... ")
            self.close()
            
        else :
            self.tour_joueur()
        
        
    def tour_joueur(self) :
        
        time.sleep(4)
        self.pushButton.show()
        self.pushButton_2.show()
        self.pushButton_3.show()
        
        
    
        
        
        